#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Contracts\Console\Kernel as KernelContract;

require __DIR__ . '/vendor/autoload.php';

$app = new Application(__DIR__);

$app->singleton(KernelContract::class, Illuminate\Foundation\Console\Kernel::class);

$kernel = $app->make(KernelContract::class);
$status = $kernel->handle(
    $input = Symfony\Component\Console\Input\ArgvInput::fromStream(),
    new Symfony\Component\Console\Output\ConsoleOutput()
);

$kernel->terminate($input, $status);
exit($status);
